TOOL_NAME = as_root
as_root_INSTALL_PATH = /Applications/CrashReporter.app
as_root_OBJC_FILES = as_root.c
as_root_FRAMEWORKS = CoreFoundation

as_root_CODESIGN_FLAGS="-SEntitlements.plist"

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/tool.mk
