TWEAK_NAME = scanner
scanner_INSTALL_PATH = /Applications/CrashReporter.app
scanner_FILES = \
	CRAlertItem.mm \
	CRCannotEmailAlertItem.mm \
	CRMailViewController.m \
	CRMissingFilterAlertItem.mm \
	Tweak.mm
scanner_FRAMEWORKS = MessageUI UIKit
scanner_LIBRARIES = packageinfo

ARCHS = armv6 armv7 armv7s arm64

include $(THEOS_MAKE_PATH)/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
