TWEAK_NAME = monitor
monitor_INSTALL_PATH = /Applications/CrashReporter.app
monitor_FILES = Tweak.mm
monitor_PRIVATE_FRAMEWORKS = SpringBoardServices

ARCHS = armv6 armv7 armv7s arm64

include $(THEOS_MAKE_PATH)/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
